joints_limit:
  arm:
    joint_1:
      has_position_limits: true
      min_position: -2.96426720159
      max_position: 2.96444173451
      has_velocity_limits: true
      max_velocity: 3.14159265358979
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 1
    joint_2:
      has_position_limits: true
      min_position: -1.7453117987
      max_position: 2.35601995727
      has_velocity_limits: true
      max_velocity: 2.87979326579064
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 1
    joint_3:
      has_position_limits: true
      min_position: -1.1836822987
      max_position: 2.56
      has_velocity_limits: true
      max_velocity: 3.45575191894877
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 1
    joint_4:
      has_position_limits: true
      min_position: -3.14421064747
      max_position: 3.13042254638
      has_velocity_limits: true
      max_velocity: 4.31968989868597
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 1
    joint_5:
      has_position_limits: true
      min_position: -0.165806278939
      max_position: 1.73677713866
      has_velocity_limits: true
      max_velocity: 4.31968989868597
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 1
    joint_6:
      has_position_limits: true
      min_position: 0.0
      max_position: 6.283185
      has_velocity_limits: true
      max_velocity: 6.91150383789755
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 1
  gripper:
    palm_finger_1_joint:
      has_position_limits: true
      min_position: -0.1784
      max_position: 0.192
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_1_joint_1:
      has_position_limits: true
      min_position: 0.0495
      max_position: 1.2218
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_1_joint_2:
      has_position_limits: true
      min_position: 0.0
      max_position: 1.5708
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_1_joint_3:
      has_position_limits: true
      min_position: -1.2217
      max_position: -0.0523
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    palm_finger_2_joint:
      has_position_limits: true
      min_position: -0.192
      max_position: 0.1784
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_2_joint_1:
      has_position_limits: true
      min_position: 0.0495
      max_position: 1.2218
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_2_joint_2:
      has_position_limits: true
      min_position: 0.0
      max_position: 1.5708
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_2_joint_3:
      has_position_limits: true
      min_position: -1.2217
      max_position: -0.0523
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_middle_joint_1:
      has_position_limits: true
      min_position: 0.0495
      max_position: 1.2218
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_middle_joint_2:
      has_position_limits: true
      min_position: 0.0
      max_position: 1.5708
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
    finger_middle_joint_3:
      has_position_limits: true
      min_position: -1.2217
      max_position: -0.0523
      has_velocity_limits: true
      max_velocity: 100
      has_acceleration_limits: false
      has_jerk_limits: false
      has_effort_limits: true
      max_effort: 100
