# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_position_limits: true
    min_position: -2.617994
    max_position: 2.617994
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 1
  joint_2:
    has_position_limits: true
    min_position: -1.047198
    max_position: 1.745329
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 1
  joint_3:
    has_position_limits: true
    min_position: 0.3141593
    max_position: 2.443461
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 1
  joint_4:
    has_position_limits: true
    min_position: -2.96706
    max_position: 2.96706
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 1
  joint_5:
    has_position_limits: true
    min_position: -1.658063
    max_position: 2.356194
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: true
    max_acceleration: 10
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 1
  joint_6:
    has_position_limits: true
    min_position: -2.96706
    max_position: 2.96706
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
    has_jerk_limits: false
    has_effort_limits: true
    max_effort: 1
  # joint_gripper:
  #   has_velocity_limits: true
  #   max_velocity: 0.04
  #   has_acceleration_limits: false
  #   max_acceleration: 0
  # joint_gripper_mimic:
  #   has_velocity_limits: true
  #   max_velocity: 0.04
  #   has_acceleration_limits: false
  #   max_acceleration: 0
